import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { EMPTY, type Data } from '../storage/model';
import type { DataBackend } from '../lib/supabase';
import { DataProvider, useData } from './DataContext';
vi.mock('./AuthContext', () => ({ useAuth: () => ({ user: { id: 'usuario-a' } }) }));
function Probe(){const{data,setData,loading,syncState,retry,warning}=useData();return <><span>{loading?'loading':`${data.notes.length}:${syncState}`}</span>{warning&&<span>{warning}</span>}<button onClick={()=>setData(d=>({...d,expenses:[...d.expenses,{id:'e',concept:'Luz',cents:100}]}))}>cambiar</button><button onClick={retry}>reintentar</button></>}
describe('DataProvider',()=>{
  afterEach(()=>{cleanup();vi.restoreAllMocks();});
  beforeEach(()=>{localStorage.clear();vi.useRealTimers();});
  it('valida y carga la fila remota sin volver a guardarla',async()=>{const remote:Data={...EMPTY,notes:[]};const update=vi.fn();const backend:DataBackend={read:vi.fn(async()=>({data:{user_id:'usuario-a',data:remote,updated_at:'r1'},error:null})),insert:vi.fn(),update};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:synced');expect(JSON.parse(localStorage.getItem('escritorio-personal-v1:usuario-a')!)).toEqual(remote);await new Promise(resolve=>setTimeout(resolve,650));expect(update).not.toHaveBeenCalled();});
  it('serializa un cambio y usa la revisión cargada',async()=>{const update=vi.fn(async(_id:string,data:Data)=>({data:{user_id:'usuario-a',data,updated_at:'r2'},error:null}));const backend:DataBackend={read:vi.fn(async()=>({data:{user_id:'usuario-a',data:EMPTY,updated_at:'r1'},error:null})),insert:vi.fn(),update};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:synced');await act(async()=>{screen.getByText('cambiar').click();await new Promise(resolve=>setTimeout(resolve,650));});await waitFor(()=>expect(update).toHaveBeenCalledWith('usuario-a',expect.objectContaining({expenses:expect.any(Array)}),'r1'));});
  it('no crea una fila si la lectura remota falla',async()=>{const insert=vi.fn();const backend:DataBackend={read:vi.fn(async()=>({data:null,error:{message:'offline'}})),insert,update:vi.fn()};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:error');expect(insert).not.toHaveBeenCalled();});
  it('reintenta la lectura inicial después de recuperar la conexión',async()=>{const read=vi.fn().mockResolvedValueOnce({data:null,error:{message:'offline'}}).mockResolvedValueOnce({data:{user_id:'usuario-a',data:EMPTY,updated_at:'r1'},error:null});const backend:DataBackend={read,insert:vi.fn(),update:vi.fn()};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:error');fireEvent.click(screen.getByText('reintentar'));await screen.findByText('0:synced');expect(read).toHaveBeenCalledTimes(2);});
  it('convierte una excepción de red en un error recuperable',async()=>{const backend:DataBackend={read:vi.fn(async()=>{throw new Error('sin red')}),insert:vi.fn(),update:vi.fn()};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:error');expect(screen.getByText(/sin red/)).toBeVisible();});
  it('rechaza una fila perteneciente a otra cuenta',async()=>{const foreign:Data={...EMPTY,expenses:[{id:'x',concept:'Privado',cents:1}]};const backend:DataBackend={read:vi.fn(async()=>({data:{user_id:'usuario-b',data:foreign,updated_at:'r1'},error:null})),insert:vi.fn(),update:vi.fn()};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:error');expect(screen.queryByText('Privado')).not.toBeInTheDocument();expect(localStorage.getItem('escritorio-personal-v1:usuario-a')).toBeNull();});
  it('detiene el guardado cuando otra revisión ganó el conflicto',async()=>{const backend:DataBackend={read:vi.fn(async()=>({data:{user_id:'usuario-a',data:EMPTY,updated_at:'r1'},error:null})),insert:vi.fn(),update:vi.fn(async()=>({data:null,error:null}))};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:synced');fireEvent.click(screen.getByText('cambiar'));await screen.findByText('0:conflict',{},{timeout:1500});expect(screen.getByText(/otro dispositivo/)).toBeVisible();});
  it('migra los datos heredados una sola vez cuando la nube está vacía',async()=>{const legacy:Data={...EMPTY,expenses:[{id:'e',concept:'Luz',cents:100}]};localStorage.setItem('escritorio-personal-v1',JSON.stringify(legacy));vi.spyOn(window,'confirm').mockReturnValue(true);const insert=vi.fn(async(_id:string,data:Data)=>({data:{user_id:'usuario-a',data,updated_at:'r1'},error:null}));const backend:DataBackend={read:vi.fn(async()=>({data:null,error:null})),insert,update:vi.fn()};render(<DataProvider backend={backend}><Probe/></DataProvider>);await screen.findByText('0:synced');expect(insert).toHaveBeenCalledWith('usuario-a',legacy);expect(localStorage.getItem('escritorio-personal-v1:migration-decided')).toBe('done');expect(JSON.parse(localStorage.getItem('escritorio-personal-v1')!)).toEqual(legacy);});
});
