import{useEffect,useState}from'react';import{useData}from'../../app/DataContext';import{id,PAGE_LIMIT,Page}from'../../storage/model';
const pagesFor=(text:string):Page[]=>{const now=new Date().toISOString();const chunks=text.match(new RegExp(`[\\s\\S]{1,${PAGE_LIMIT}}`,'g'))??[''];return chunks.map(text=>({id:id(),text,createdAt:now}))};
export function Journal(){const{data,setData}=useData();const[selected,setSelected]=useState(data.folders[0]?.id??'');const[page,setPage]=useState(0);const folder=data.folders.find(f=>f.id===selected);
 useEffect(()=>{if(!data.folders.some(f=>f.id===selected)){setSelected(data.folders[0]?.id??'');setPage(0)}},[data.folders,selected]);useEffect(()=>{if(folder)setPage(p=>Math.min(p,Math.max(0,folder.pages.length-1)))},[folder]);
 const addFolder=()=>{const name=prompt('Nombre de la carpeta')?.trim();if(!name)return;const fid=id();setData(d=>({...d,folders:[...d.folders,{id:fid,name,pages:pagesFor('')}]}));setSelected(fid);setPage(0)};
 const renameFolder=()=>{if(!folder)return;const name=prompt('Nuevo nombre de la carpeta',folder.name)?.trim();if(!name)return;setData(d=>({...d,folders:d.folders.map(f=>f.id===folder.id?{...f,name}:f)}))};
 const deleteFolder=()=>{if(!folder||!confirm(`¿Borrar la carpeta “${folder.name}” y todas sus hojas?`))return;const index=data.folders.findIndex(f=>f.id===folder.id);const next=data.folders[index+1]??data.folders[index-1];setSelected(next?.id??'');setPage(0);setData(d=>({...d,folders:d.folders.filter(f=>f.id!==folder.id)}))};
 const write=(value:string)=>{if(!folder)return;const chunks=pagesFor(value);setData(d=>({...d,folders:d.folders.map(f=>{if(f.id!==folder.id)return f;const current=f.pages[page]??pagesFor('')[0];const replacement=chunks.map((p,i)=>i===0?{...current,text:p.text}:p);return{...f,pages:[...f.pages.slice(0,page),...replacement,...f.pages.slice(page+1)]}})}));if(chunks.length>1)setPage(page+chunks.length-1)};
 return <section><div className="section-title"><div><p className="eyebrow">Recuerdos y pensamientos</p><h1>Mi diario</h1></div><button onClick={addFolder}>Nuevo diario</button></div><div className="journal-layout"><aside><h2>Carpetas</h2>{data.folders.map(f=><button className={selected===f.id?'active':''} onClick={()=>{setSelected(f.id);setPage(0)}} key={f.id}>{f.name}</button>)}</aside>{folder?<div className="journal-content"><div className="folder-actions" aria-label="Acciones de carpeta"><button onClick={renameFolder}>Editar nombre</button><button className="delete" onClick={deleteFolder}>Borrar diario</button></div><div className="book"><div className="book-ribbon" aria-hidden="true"/><div className="paper"><div className="page-meta">{folder.name} · Hoja {page+1} de {folder.pages.length}</div><textarea aria-label="Página del diario" value={folder.pages[page]?.text??''} onChange={e=>write(e.target.value)} placeholder="Escribí aquí lo que quieras recordar…"/><small>{folder.pages[page]?.text.length??0} / {PAGE_LIMIT}</small></div><div className="page-buttons"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>← Hoja anterior</button><span aria-hidden="true">— {page+1} —</span><button disabled={page>=folder.pages.length-1} onClick={()=>setPage(p=>p+1)}>Hoja siguiente →</button></div></div></div>:<div className="empty"><h2>Tu diario está listo</h2><p>Creá una carpeta para comenzar a escribir.</p><button onClick={addFolder}>Crear mi primera carpeta</button></div>}</div></section>}
